version: 2

sources:
  - name: practice_case_4
    description: dataset for practice case 4
    tables:
      - name: external_raw_nyt_yellowtrip
        columns:
        - name: VendorID
          description: "A code indicating the TPEP provider that provided the record."
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
            - accepted_values:
                values: [1, 2]
                severity: warn
        - name: tpep_pickup_datetime
          description: "The date and time when the meter was engaged."
        - name: tpep_dropoff_datetime
          description: "The date and time when the meter was disengaged."
        - name: passenger_count
          description: "The number of passengers in the vehicle."
        - name: trip_distance
          description: "The elapsed trip distance in miles reported by the taximeter."
        - name: RatecodeID
          description: "The final rate code in effect at the end of the trip."
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
            - accepted_values:
                values: [1, 2, 3, 4, 5, 6]
                severity: warn
        - name: store_and_fwd_flag
          description: "This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server"
        - name: PULocationID
          description: "Pickup location ID when the taximeter was engaged."
        - name: DOLocationID
          description: "Dropoff location ID when the taximeter was disengaged."
        - name: payment_type
          description: "A numeric code signifying how the passenger paid for the trip."
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
            - accepted_values:
                values: [1, 2, 3, 4, 5, 6]
                severity: warn
        - name: fare_amount
          description: "Time-and-distance taxi fare fee calculated by the meter"
        - name: extra
          description: "Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges."
        - name: mta_tax
          description: "$0.50 MTA tax that is automatically triggered based on the metered rate in use."
        - name: tip_amount
          description: "Tip amount, This field is automatically populated for credit card tips. Cash tips are not included."
        - name: tolls_amount
          description: "Total amount of all tolls paid in trip."
        - name: improvement_surcharge
          description: "$0.30 improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015."
        - name: total_amount
          description: "The total amount charged to passengers. Does not include cash tips."
        - name: congestion_surcharge
          description: "Total amount collected in trip for NYS congestion surcharge."
      # - name: stg_dim_RatecodeID
      #   columns:

models:
  - name: fact_nytrip_data_yellow
    description: "Fact table transform after having its null values removed and ordered by date in a descending order"

